version: '3'
services:
  mongo_db:
    image: 'mongo:4.4.3'
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db-data:/var/lib/mongodb
  app:
    build: ./
    restart: on-failure
    depends_on:
      - mongo_db
    ports:
      - 8080:8080

volumes:
  db-data: